const airbtn=document.querySelector(".air-button");
const ttip=document.querySelector(".tooltip");
const tttext=document.querySelector(".tooltiptext");
const headdrop=document.querySelector(".head-drop");
const tabs = document.querySelector(".tabs");
const blankp=document.querySelector(".path-blank");
headdrop.addEventListener("click",()=>{
    tabs.classList.toggle("hide");
    americas.style.border="none";
    americas.style.borderBottom="1px solid rgb(218, 218, 218)";
    me.style.border="none";
    me.style.borderBottom="1px solid rgb(218, 218, 218)";
    afr.style.border="none";
    afr.style.borderBottom="1px solid rgb(218, 218, 218)";
    ap.style.border="none";
    ap.style.borderBottom="1px solid rgb(218, 218, 218)";
    eur.style.border="none";
    eur.style.borderBottom="1px solid rgb(218, 218, 218)";
})
const countries1 = document.querySelector(".countries1");
const countries2 = document.querySelector(".countries2");
const countries3 = document.querySelector(".countries3");
const countries4 = document.querySelector(".countries4");
const countries5 = document.querySelector(".countries5");
const add1 = document.querySelector(".add1");
const minus1 = document.querySelector(".minus1");
const add2 = document.querySelector(".add2");
const minus2 = document.querySelector(".minus2");
const add3 = document.querySelector(".add3");
const minus3 = document.querySelector(".minus3");
const add4 = document.querySelector(".add4");
const minus4 = document.querySelector(".minus4");
const add5 = document.querySelector(".add5");
const minus5 = document.querySelector(".minus5");
let americas = document.querySelector(".americas");
let me = document.querySelector(".me");
let afr = document.querySelector(".afr");
let ap = document.querySelector(".ap");
let eur = document.querySelector(".eur");
americas.addEventListener("click", () => {
  americas.style.border="1px solid #f3cb17ff";
  countries1.classList.toggle("hide");
  add1.classList.toggle("hide");
  minus1.classList.toggle("hide");
  countries2.classList.add("hide");
  add2.classList.remove("hide");
  minus2.classList.add("hide");
  me.style.border="none";
  me.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries3.classList.add("hide");
  add3.classList.remove("hide");
  minus3.classList.add("hide");
  afr.style.border="none";
  afr.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries4.classList.add("hide");
  add4.classList.remove("hide");
  minus4.classList.add("hide");
  ap.style.border="none";
  ap.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries5.classList.add("hide");
  add5.classList.remove("hide");
  minus5.classList.add("hide");
  eur.style.border="none";
  eur.style.borderBottom="1px solid rgb(218, 218, 218)";
  ttip.classList.toggle("hide");
});
me.addEventListener("click", () => {
  countries2.classList.toggle("hide");
  add2.classList.toggle("hide");
  minus2.classList.toggle("hide");
  me.style.border="1px solid #f3cb17ff";
  countries1.classList.add("hide");
  add1.classList.remove("hide");
  minus1.classList.add("hide");
  americas.style.border="none";
  americas.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries3.classList.add("hide");
  add3.classList.remove("hide");
  minus3.classList.add("hide");
  afr.style.border="none";
  afr.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries4.classList.add("hide");
  add4.classList.remove("hide");
  minus4.classList.add("hide");
  ap.style.border="none";
  ap.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries5.classList.add("hide");
  add5.classList.remove("hide");
  minus5.classList.add("hide");
  eur.style.border="none";
  eur.style.borderBottom="1px solid rgb(218, 218, 218)";
  ttip.classList.toggle("hide");
});
afr.addEventListener("click", () => {
  countries3.classList.toggle("hide");
  add3.classList.toggle("hide");
  minus3.classList.toggle("hide");
  afr.style.border="1px solid #f3cb17ff";
  countries1.classList.add("hide");
  add1.classList.remove("hide");
  minus1.classList.add("hide");
  americas.style.border="none";
  americas.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries2.classList.add("hide");
  add2.classList.remove("hide");
  minus2.classList.add("hide");
  me.style.border="none";
  me.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries4.classList.add("hide");
  add4.classList.remove("hide");
  minus4.classList.add("hide");
  ap.style.border="none";
  ap.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries5.classList.add("hide");
  add5.classList.remove("hide");
  minus5.classList.add("hide");
  eur.style.border="none";
  eur.style.borderBottom="1px solid rgb(218, 218, 218)";
  ttip.classList.toggle("hide");
});
ap.addEventListener("click", () => {
  countries4.classList.toggle("hide");
  add4.classList.toggle("hide");
  minus4.classList.toggle("hide");
  ap.style.border="1px solid #f3cb17ff";
  countries1.classList.add("hide");
  add1.classList.remove("hide");
  minus1.classList.add("hide");
  americas.style.border="none";
  americas.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries2.classList.add("hide");
  add2.classList.remove("hide");
  minus2.classList.add("hide");
  me.style.border="none";
  me.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries3.classList.add("hide");
  add3.classList.remove("hide");
  minus3.classList.add("hide");
  afr.style.border="none";
  afr.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries5.classList.add("hide");
  add5.classList.remove("hide");
  minus5.classList.add("hide");
  eur.style.border="none";
  eur.style.borderBottom="1px solid rgb(218, 218, 218)";
  ttip.classList.toggle("hide");
});
eur.addEventListener("click", () => {
  countries5.classList.toggle("hide");
  add5.classList.toggle("hide");
  minus5.classList.toggle("hide");
  eur.style.border="1px solid #f3cb17ff";
  countries1.classList.add("hide");
  add1.classList.remove("hide");
  minus1.classList.add("hide");
  americas.style.border="none";
  americas.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries2.classList.add("hide");
  add2.classList.remove("hide");
  minus2.classList.add("hide");
  me.style.border="none";
  me.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries3.classList.add("hide");
  add3.classList.remove("hide");
  minus3.classList.add("hide");
  afr.style.border="none";
  afr.style.borderBottom="1px solid rgb(218, 218, 218)";
  countries4.classList.add("hide");
  add4.classList.remove("hide");
  minus4.classList.add("hide");
  ap.style.border="none";
  ap.style.borderBottom="1px solid rgb(218, 218, 218)";
  ttip.classList.toggle("hide");
});